services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=global'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'  # Certifique-se de que a porta local (host) está vinculada à porta do container
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
